version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fitdojo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: fitdojo-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"  # UI
      - "1025:1025"  # SMTP

volumes:
  pgdata:
